### ISSUE TITLE
red/magenta issues

### ISSUE THREAD

**Issue by dnkl** [CosmicToast/starlight#3] opened 2023-07-14 06:28 UTC
This is a continuation of the discussion started in https://codeberg.org/dnkl/foot/pulls/1331

In short, the red and magenta (and at least for me, the red in particular) are a bit hard to read. Not excessively so, but still a bit worse than the other colors.

At least for me, it's perceived as red and magenta almost being a bit blurry.

Relevant comments from the codeberg issue

> _This theme maybe helpful for colorblind people but it does have some accessibility issues_
> 
> _* the red color (CF1745) fails WCAG AA and AAA against the background (242424)_
> _* the magenta color (D926AC) also fails WCAG AA and AAA against the background (242424)_
>
> _The lightness values of the colors on the CIELAB color space are also considerably different which makes the perception of colors to be skewed._

https://codeberg.org/dnkl/foot/pulls/1331#issuecomment-891796

and

> _I personally think this would be a fairly good default theme. I do however agree with [@ayushnix](https://codeberg.org/ayushnix) that the magenta, and red in particular, are a bit hard to read._
>
> _[@helene](https://codeberg.org/helene) have you considered upping their intensity levels a bit? Or darkening the background?_
>
> _FWIW, the bright colors appear to be fine._

https://codeberg.org/dnkl/foot/pulls/1331#issuecomment-979642

**Comment by dnkl** [comment] 2023-07-14 06:30
> The lightness values of the colors on the CIELAB color space are also considerably different which makes the perception of colors to be skewed.

I personally don't consider this as important as the weak red/magenta colors (hence I didn't even mention it in the issue title, or description (other than in the pasted comment).

**Comment by CosmicToast** [comment] 2023-07-14 07:55
I've already added a new WCAG-like tester (atm it uses an API but it may be possible to reproduce the algorithm in shell) in `colors/wcag.sh`.
In short, it programmatically determines contrast ratio to background, with in-script configurable warn and fail thresholds (currently set to the WCAG AAA and AA recommendations respectively).
I'll try and see if I can do anything re the two colors.
Initial impressions are that darkening the background (e.g to 161616) just makes it look worse without significantly impacting contrast, while trying to naively bump luminance up enough ends up leaving no space for a "bright" variant.
I'm sure I'll find something though.

**Comment by CosmicToast** [comment] 2023-07-14 09:44
The v4 branch is an attempt at a "rewrite" using Lch as a base instead of HSV.
Here's a preview: 
<img width="368" alt="image" src="https://github.com/CosmicToast/starlight/assets/5273047/9ab45895-39c9-40fd-a7dc-2ba2f319c652">

Any opinions @dnkl ?
I've already checked for colorblindness things, and aimed for a 4:1 contrast ratio (slightly lower than "even" WCAG AA, but seems to be alright).

I discovered that the lightness values being "all over the place" is inevitable in this specific use-case, but I think I got it to work and still be "recognizably" starlight.

To be clear, the *first* demo is the current v3, the *second* demo is the potentially-new v4.
Explanation as to the model is in the changes document.
The main changes that may still happen are to the cyan - which may be tweaked further green.

**Comment by dnkl** [comment] 2023-07-14 09:57
The red is definitely more readable now! So is the new magenta (and I personally prefer its new shade over the old one).

As for the other colors, I'm fine with the new versions, though I _do_ prefer the old cyan over the new one. Or rather, for me (who suffers no color blindness at all, as far as I know), the old cyan/blue were more easily distinguishable than the new ones). I might also have a _slight_ preference for the old green variant... But all this is something I leave up to you; all colors in v4 are readable (to me).

**Comment by CosmicToast** [comment] 2023-07-14 10:10
I will most likely change the cyan, since with my color blindness my ability to differentiate it from the blue is not absent, but conditional. I will make it closer to the old one (more green), though this may require more L and C fiddling.
I'll take a look at the green differences.

Likely over this weekend for both of these.
Once everyone's happy with the new values I'll merge v4 in.

**Comment by dnkl** [comment] 2023-07-14 10:13
If I release foot today, would you prefer I use v3, or v4 as it is now? I would probably prefer v4 as it is.

As I've already mentioned, I'll do a patch release of foot once v4 is done, but it may not happen immediately.

**Comment by CosmicToast** [comment] 2023-07-14 10:19
I would say v3, since it's an actual "finalized" version. I don't like putting my name on exploratory unfinished things.
V3 has been used for almost a year now, so it's generally ok.
If you wanted to have a temporary patch, you could use v3 with v4 reds and magentas (since those are most likely going to stay).

**Comment by dnkl** [comment] 2023-07-14 10:22
> I don't like putting my name on exploratory unfinished things.

No worries, I definitely understand that. I'll go with v3 :)

**Comment by CosmicToast** [comment] 2023-07-14 14:32
An updated cyan.
<img width="752" alt="image" src="https://github.com/CosmicToast/starlight/assets/5273047/5afed021-60c6-4561-a10e-592ec44ef816">
About 20 hue points more "green" for both, much more differentiable to me.
If I have no more improvement ideas I'll test drive it for a week or two before release.

**Comment by CosmicToast** [comment] 2023-07-14 16:24
New magentas.
<img width="752" alt="image" src="https://github.com/CosmicToast/starlight/assets/5273047/d29aa4a1-547a-48ff-a84a-68bfd4145819">
In the end they were too close to the blues and cyans if you have protanopia or deuteranopia, after which it took a bit to adjust them otherwise.
Magenta is really the worst color for this, since directly left of it hue-wise is blue (tritanopia) and directly right of it is red...
Because of this, I went the borderline pastel route, so it can be differentiated via luminance.

**Comment by CosmicToast** [comment] 2023-07-17 16:44
This has been merged, so I'm closing.
Potential revisit points for v5 would be the red, which has a contrast ratio of 4:1 (which is a bit low, but seems to still be readable to everyone I've asked to check).
Similarly to magenta, it's very non-trivial to make it contrast well while still fitting into sRGB...
Regardless, should be good for the point release @dnkl 
If people complain, I could advance the v5 schedule, but IMO this is still a big improvement over the previous versions (which were already much better than most other options I've had the mispleasure of dealing with, maybe besides tango).

**Closed as completed by CosmicToast** 2023-07-17 16:44 UTC

**Comment by CosmicToast** [comment] 2023-07-17 16:47
P.S. I ported the contrast checker into `contrast.sh`.
The output looks like this now:
<img width="752" alt="image" src="https://github.com/CosmicToast/starlight/assets/5273047/9e41f2ce-79d7-46dd-8a52-f9f14fb4d31b">
There's an unfortunate bug re: precision loss, since POSIX bc does not support non-integer exponentiation, which means I have to emulate it using e() and l(). The color did not change from the previous iteration, and it is still "truly" 4.0. Values close to target should just be evaluated by a human.
Part of my goals with starlight were also to have a sort of "starting off" point for other people making ANSI themes - basically establishing tooling and generation systems. Just change `colors.sh` and you just have foot support etc built-in :)

**Comment by dnkl** [comment] 2023-07-18 14:21
Looks good to me, appreciate your work! PR for foot: https://codeberg.org/dnkl/foot/pulls/1413
